server {
    listen 80;
    server_name _; # On changera ça plus tard avec ton nom de domaine OVH

    # 1. Si on tape l'URL normale, Nginx redirige vers le site Angular
    location / {
        proxy_pass http://frontend:80;
    }

    # 2. Si l'URL contient /api/panier, Nginx redirige vers le port 8000 du backend
    location /api/panier {
        proxy_pass http://backend:8000/api/panier;
    }

    # 3. Si l'URL contient /api/produits, Nginx redirige vers le port 8080 du backend
    location /api/produits {
        proxy_pass http://backend:8080/api/produits;
    }
}